const items = [
    {
      id: '001',
      image: '/images/uspolo1.avif',
      company: 'US Polo Assn.',
      item_name: 'Men Solid Polo Collar T-shirt',
      original_price: 1499,
      current_price: 1049,
      discount: 30,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.5,
        count: 4100,
      },
    },
    {
      id: '002',
      image: '/images/uspolo2.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Men Solid Polo Collar T-shirt',
      original_price: 1499,
      current_price: 1049,
      discount: 30,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.5,
        count: 4100,
      },
    },
    {
      id: '003',
      image: '/images/uspolo3.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Men Skinny Fit Mid-Rise Jeans',
      original_price: 2399,
      current_price: 1699,
      discount: 29,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.4,
        count: 2700,
      },
    },
    {
      id: '004',
      image: '/images/uspolo4.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Men Printed Hooded Sweatshirt',
      original_price: 2499,
      current_price: 1499,
      discount: 40,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.6,
        count: 5000,
      },
    },
    {
      id: '005',
      image: '/images/uspolo5.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Men Quilted Jacket with Hood',
      original_price: 4999,
      current_price: 2999,
      discount: 40,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.7,
        count: 1900,
      },
    },
    {
      id: '006',
      image: '/images/uspolo6.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Men Cotton Regular Fit Track Pants',
      original_price: 1299,
      current_price: 899,
      discount: 31,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.3,
        count: 1600,
      },
    },
    {
      id: '007',
      image: '/images/uspolo7.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Genuine Leather Bi-Fold Wallet',
      original_price: 999,
      current_price: 799,
      discount: 20,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.5,
        count: 2300,
      },
    },
    {
      id: '008',
      image: '/images/uspolo8.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Men Embroidered Baseball Cap',
      original_price: 799,
      current_price: 499,
      discount: 38,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.6,
        count: 1100,
      },
    },
    {
      id: '009',
      image: '/images/uspolo9.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Textured Reversible Leather Belt',
      original_price: 1499,
      current_price: 949,
      discount: 37,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.2,
        count: 870,
      },
    },
    {
      id: '010',
      image: '/images/uspolo10.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Textured Reversible Leather Belt',
      original_price: 1499,
      current_price: 949,
      discount: 37,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.2,
        count: 870,
      },
    },
    {
      id: '011',
      image: '/images/uspolo11.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Textured Reversible Leather Belt',
      original_price: 1499,
      current_price: 949,
      discount: 37,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.2,
        count: 870,
      },
    },
    {
      id: '012',
      image: '/images/uspolo12.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Textured Reversible Leather Belt',
      original_price: 1499,
      current_price: 949,
      discount: 37,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.2,
        count: 870,
      },
    },
    {
      id: '013',
      image: '/images/tommy.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Textured Reversible Leather Belt',
      original_price: 1499,
      current_price: 949,
      discount: 37,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.2,
        count: 870,
      },
    },
    {
      id: '014',
      image: '/images/levis.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Textured Reversible Leather Belt',
      original_price: 1499,
      current_price: 949,
      discount: 37,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.2,
        count: 870,
      },
    },
    {
      id: '015',
      image: '/images/flyingmachine.jpeg',
      company: 'US Polo Assn.',
      item_name: 'Textured Reversible Leather Belt',
      original_price: 1499,
      current_price: 949,
      discount: 37,
      return_period: 14,
      delivery_date: '30 Apr 2025',
      rating: {
        stars: 4.2,
        count: 870,
      },
    },
  ];
  